# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "891ef7727471c47ae24ced0e1057d86a"
name = "v-mirror-spf"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_themes,write_files,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://arnold-experiments-cleanup-yorkshire.trycloudflare.com"
subpath = "v-mirror"
prefix = "apps"
